---
title: "Endangered species critical habitat for sale"
author: "Emily"
date: "5/26/2021"
output: html_document
summary: "Land over 100 acres for sale in endangered species habitats"
tags:
- R
- GIS
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, echo=F}
library(leaflet,RColorBrewer)

substrRight <- function(x, n){
  substr(x, nchar(x)-n+1, nchar(x))
}

pathtofile <- "~/Google Drive/My Drive/fka_Dropbox/Landcheck/alllandwatchcrithab_2021-05-26.csv"
dat=read.csv(pathtofile)
data_date <- substr(substrRight(pathtofile,14),1,10)


badcolnames <- colnames(dat)
goodcolnames <- c(badcolnames[2:(ncol(dat)-1)],"longitude","latitude")

colnames(dat) <- goodcolnames

dat$longitude <- as.numeric(substr(dat$longitude,3,nchar(as.character(dat$longitude))))
dat$latitude <-as.numeric(gsub(")","",dat$latitude))

dat <- dat[dat$price>1000,]
dat$logacreprice <- log(dat$acreprice)

```
## 

<font size = "1">Image license:
<a href="https://commons.wikimedia.org/wiki/User:Famartin"> Famartin </a>, <a href = "https://commons.wikimedia.org/wiki/File:2014-06-28_11_25_56_Big_sagebrush_on_the_northwestern_slopes_of_Twin_Peaks_near_Elko,_Nevada.JPG "> 2014-06-28 11 25 56 Big sagebrush on the northwestern slopes of Twin Peaks near Elko, Nevada </a>, <a href=" https://commons.org .commons.org -sa / 3.0 / legalcode "rel =" license "> CC BY-SA 3.0 </a></font>

<font size = "3"> This map shows undeveloped land in the US listed for sale on landwatch.com. For now, I have filtered it to listings for >100 acres that occur in the ranges of IUCN designated endangered species. </font>

##

```{r, echo=F, fig.width=14, fig.height=12, fig.align='center'}
#pricepal <- colorRampPalette(brewer.pal(7,"Greens"))(100)
#comname = "Bachman's sparrow"

pal <- colorNumeric(
  palette = colorRampPalette(c('green', 'red'))(length(dat$logacreprice)), 
  domain = dat$logacreprice)

m <- leaflet(data=dat)  %>% addTiles() %>% addCircleMarkers(color =  ~pal(dat$logacreprice)) %>%#, radius = dat$acres/500) %>%
 # addProviderTiles(providers$Esri.WorldImagery) %>%  # Add default OpenStreetMap map tiles
#  setView(-96.7, 25.8, zoom = 3) %>%
  addMarkers(~longitude, ~latitude, popup=~paste0(comname,", ",acres," acres in ",city,", ",state,  ": ", ' <a href="https://www.landwatch.com',canonicalUrl,'"> See listing </a>'))

m
```
```{r, echo=F}
print(paste("Land listing data retrieved",data_date))
print(paste("Total listings found in endangered species habitat:",nrow(dat)+1))
```
